### ISSUE TITLE
CZI proposal on accessibility: steering council approval 

### ISSUE THREAD

**Issue by trallard** [jupyter/governance#100]
Hey y'all

I am opening this issue as @isabela-pf @tonyfast and I are working on a CZI EOSS proposal on accessibility for Jupyter

See issue: https://github.com/jupyter/accessibility/issues/36
Submitted letter of intent: https://github.com/jupyter/accessibility/pull/44

I know there is no formal process (yet) to apply for funding but there are a couple of discussions happening in #96  and #97 hence I would like to request formal approval from the steering council to move forward with this work

Let me know if there is any other information I'd need to provide

**Comment by Carreau** [comment]
I Approved both.

disclosure: I work at Quansight with @trallard.

**Comment by minrk** [comment]
Enthusiastic support from me!

**Comment by fperez** [comment]
I haven't been involved with the accessibility work for a while, but I'm delighted to see forward motion on this! 

Just to note, as I looked around the relevant materials I saw [you posted the proposal draft](https://docs.google.com/document/d/1HxoZTDKuHz58VEPpHYJDloMfHFkbxCJNKOu84OYvylI/edit) (thx for doing that, just linking it here as it's relevant for anyone giving feedback/input).

I'm enthusiastically in support of this work - I trust you've all coordinated on the [accessibility repo](https://github.com/jupyter/accessibility) so that all the relevant folks are in the loop.  Specifically, from an (admittedly quick) reading of the proposal draft, I see that in addition to documentation and overall assessment of accessibility issues, you have some technical aims on a few specific projects - the pydata sphinx theme, jupyterbook and jupyterlab. I think it would be valuable to have feedback from some of those teams that they're +1 on the proposed ideas/plan to ensure good overall coordination.

But assuming that such coordination is in place (at a high-level, obviously, given it's early stages and not even funded yet), a very enthusiastic +1 from me, combined with gratitude that you're tackling this critical area of the project!

**Comment by fperez** [comment]
ps - I also sent a quick reminder to the steering council list so we get as much feedback as possible. We're doing our best to *not* have private discussions in the SC list so everyone participates here, but a little "heads up" email to that list is often useful to remind folks to come back here to the public spaces :)

**Comment by willingc** [comment]
> I'm enthusiastically in support of this work - I trust you've all coordinated on the accessibility repo so that all the relevant folks are in the loop

@fperez They certainly have :smile: https://github.com/jupyter/accessibility/pull/44

+1 from me.

**Comment by ivanov** [comment]
I support this effort, thank you for coordinating it!

**Comment by willingc** [comment]
@fperez Can this be closed now that the proposal has been submitted.

**Comment by damianavila** [comment]
> Can this be closed now that the proposal has been submitted.

I am not @fperez but I think we can close it now :wink:
