### ISSUE TITLE
Create trademark usage policy

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/governance#12]
We need to have an official policy that clarifies how 3rd parties can use our jupyter tradmarks (name and logos).

**Comment by ellisonbg** [comment]
Good example:

https://www.python.org/psf/trademarks/

**Comment by fperez** [comment]
Yup, the PSF ones should be our starting point. The [logo page](https://www.python.org/community/logos/) is also useful, it's complementary (and refers to the above for trademark details).

**Comment by williamstein** [comment]
Here's a concrete question to clarify your policy.  In the Python rules, it says 

> For the python rules they want to copy: ‘Any commercial use of the PSF trademarks in product or company names must be approved first by the PSF. Some uses, like calling a company “The Python Company,” or a product “Python Language” or “Python IDE” will be refused. This is because they are overly broad, or confusing as to whether the Python programming language is open source or commercial, or whether your product or organization is affiliated with or sponsored by PSF.’

If I would like to make a version of SageMathCloud that has a strong Jupyter preference (so the default is Jupyter rather than Sagews, etc.,) and has the domain name like awesomejupyternotebooks.com (say), would you guys say "yes" or "no" to my request?

**Comment by fperez** [comment]
Mmh, that sounds very similar to the examples the PSF gives for uses that would be likely refused...

Honestly, we're not trademark lawyers, so we'd probably need advice from one. I really want our policy to be as inclusive as possible, while letting us defend the trademarks from abuse (which is a right you lose if you don't defend it). For example, there are companies like pythonanywhere.com or laclinux.com that use the Python/Linux trademarks but are independent from the PSF/Linux Foundation. So evidently certain uses are acceptable.

We are working right now on some trademark-related issues, so hopefully soon we'll have more clarity on this. Is this a specific request or only hypothetical? If it's specific, feel free to ping us via email (since I imagine you wouldn't want to divulge the name in public) and we can perhaps provide better guidance and figure out a way to get legal advice on it.

**Comment by williamstein** [comment]
It's been pointed out to me by many people that using a domain name like foojupyterbar.com could easily be very confusing to users.  However, using a subdomain like `jupyter.sagemath.com`, or even just a url schema starting with jupyter, e.g., `sagemath.com/jupyter/...` would prevent confusion and clarify the connection with SageMath.   So I would also like to ask the steering committee about those two additional types of use.

**Comment by Carreau** [comment]
I can see how `sagemath.com/jupyter/...` might be annoying for some implementation, in particular if you want to refer to an absolute resource, and many website treat the subdomain differetly (like hackernew used to show everything as "just" github.com), but it's true that it can be a usefull first step.

I also just realised that despite this being posted here, I never got notifications so never saw this thread, and this repository was not on my watch list. Likely a mistake from my part, so apologies. This is now corrected, I'm watching this repository, and will ask the council if they've seen this thread [as well as forward the request about subdomain]

Thanks !

**Comment by jasongrout** [comment]
@williamstein forwarded a list of 14 other domains that have "jupyter" in the title (including, of course, jupyter.org). I didn't see any that seemed to create confusion with Project Jupyter, though.

**Comment by minrk** [comment]
I would think that subdomain/sub-path would be sufficient signal that it's "Jupyter provided by sagemath", etc. The gist seems to me to be that if it's clear that Jupyter refers to the Jupyter parts being served, and not the service provider itself, things are okay.

**Comment by williamstein** [comment]
Another name we're looking at:  https://jupyter.CoCalc.com      Here "CoCalc" is supposed to mean "Collaborative Calculation" and the point is that we would be a place that you can use Jupyter collaboratively online to do calculations.     But as you say, it's clearer from this name that this is part of the CoCalc project, not Jupyter itself.    I think this discussion is really productive.

**Comment by Carreau** [comment]
@williamstein did you already registered this one ? [just to be sure no-one grab it from you].

**Comment by williamstein** [comment]
@Carreau -- yep; thanks for your concern.

**Comment by Carreau** [comment]
> @Carreau -- yep; thanks for your concern.

Ok, great.

**Comment by jasongrout** [comment]
@williamstein - an update - your current request using jupyter in a subdomain or path is under discussion on the steering council list.

**Comment by zommuter** [comment]
related: https://news.ycombinator.com/item?id=12169979 and http://sagemath.blogspot.com/2016/07/jupyter-take-domain-name-down.html

**Comment by oschuett** [comment]
I was wondering if there is now an official policy on using jupyter as a subdomain?

**Comment by minrk** [comment]
Using jupyter in a subdomain or url path is explicitly allowed in the draft trademark policy: https://github.com/jupyter/governance/blob/12311010f08b08ff93ce6cefd01a5704cae6f458/trademarks.md#examples

**Comment by oschuett** [comment]
Great! Thanks for the quick reply.

**Comment by damianavila** [comment]
I just merged https://github.com/jupyter/governance/pull/22, closing this one now.
