### ISSUE TITLE
Contacting EC clarifications

### ISSUE THREAD

**Issue by krassowski** [jupyter/governance#171]
1) Are issues here monitored? If not, would adding an issue template saying "please post/send message here/there instead" be helpful?
2) What is the place I can ask for small actions which require bothering someone from EC but are not really worth (or at least in my opinion should not require) writing up an email? For example "who has merge rights and can merge a single line change over at https://github.com/jupyter/surveys/pull/24.
3) Is there a guidaince on which topics should be discussed here, which in https://github.com/jupyter/executive-council-team-compass  and which on discourse? Currently the [documentation only mentions the team compass](https://jupyter.org/governance/executive_council.html#contacting-the-executive-council), issues in this repository are not mentioned at all.

**Comment by Carreau** [comment]
I have the commit rights to merge https://github.com/jupyter/surveys/pull/24 if needs be. Le me know if you wish me to do it but I do not want to overstep.

**Comment by blink1073** [comment]
I'd say general governance questions should go here, and items for the EC should either be sent to our email account or raised as an issue on https://github.com/jupyter/executive-council-team-compass.

**Comment by blink1073** [comment]
@Carreau, please feel free to merge

**Comment by fperez** [comment]
Thanks @krassowski for bringing this up! This week we discussed it in the EC meeting and came up with the plan below... I'll post it here for now in case anyone has feedback, and if we all agree, we can also copy it to the main EC docs in the repo.  I tried to capture our Tuesday discussion as well as additional input from @Ruv7 and @blink1073 above. Thanks all!

## Contacting the Jupyter Executive Council

To contact [the Jupyter Executive Council (EC)](https://github.com/orgs/jupyter/teams/executive-council), please choose the option that best fits your needs:

* [Issues on the EC Team Compass repository](https://github.com/jupyter/executive-council-team-compass/issues): for _open, public discussion_. We monitor this repository and allocate time on our regular weekly meetings to triage open and active issues.
* [EC mailing list](mailto:jupyter-executive-council@googlegroups.com): for _private communication_ with the EC, email our list, which is open for public posting (with archive private to EC members).
* [Bi-weekly EC Office Hours Zoom call](https://zoom.us/j/2264645576?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09): for _synchronous, public conversation_, you can join our office hours call, which is listed [in the project Google Calendar](https://discourse.jupyter.org/t/jupyter-community-calendar/2485). You can add [topics to the agenda](https://docs.google.com/document/d/1N5jm0VJlDUX4WK0n7Ia8Ff63RdzNYkH28PkSZPdBtUc/edit?usp=sharing) with additional details/references prior to the meeting.

EC members allocate time during our weekly scheduled meetings to review new issues, incoming communications, and active open issues.

**Other Channels:**
* [Issues on the main Governance Repository](https://github.com/jupyter/governance): offer a space for broader discussion about Governance with the entire community, and are better suited for conversations where input from bodies like the [Software Steering Council](https://jupyter.org/governance/software_steering_council.html), project teams and individuals are sought. **If you need to flag an issue specifically for input by the EC, please tag the team with `@executive-council`**.  The EC will move issues between this general Governance repo and the EC team compass when appropriate.
* [The Governance category on Discourse](https://discourse.jupyter.org/c/meta/governance/23): is _not formally monitored by the EC_, due to limited bandwidth. It is OK for the community to discuss governance topics there and EC members may occasionally post, but we can not commit to actively monitoring it.

**Comment by fperez** [comment]
This info is now captured in our docs as per [this PR](https://github.com/jupyter-governance/ec-team-compass/pull/22), closing this issue now so we track it in a more official location.
