### ISSUE TITLE
Adding CoC guidelines for enforcing incidents in public forums that don't require an official report

### ISSUE THREAD

**Issue by choldgraf** [jupyter/governance#68]
Hey all - a few times now we have had people show up on the community forum (I think this has happened on the listserv as well but we don't really have control over the tech there as much) being rude, unhelpful, or otherwise confrontational.

I have a personal approach to how I deal with these situations (generally, a polite note of what the person is doing wrong and locking the thread) but I think it'd be helpful for Jupyter to have guidelines for how people should handle these situations in general.

I believe that these kinds of situations don't merit an official CoC violation report, since usually it is from people who aren't active in the community and going through an official process for every jerk on the internet would be a time-consuming process. Instead some language about "if you fail to abide by XXX rules in public forums that Jupyter controls, you can expect YYY to happen" would be helpful.

What do people think about this? If folks are +1 I can add some language in a PR.

**Comment by jasongrout** [comment]
I think you handled a recent situation really well, and I agree that adding some language about possible ways to address things like locking threads with an example coment would be helpful, so thanks!

In addition to what you've said in a recent situation, I would also add an explicit invitation to please open a new issue/post with a more constructive take, i.e., reassure the person that we *do* want to discuss their honest concerns, and that we are only locking because of the way they expressed things.

I also think it's important to close/lock an initially disrespectful post and reset the tone of the conversation in a new post, even if a person comes back and wants to interact more constructively in the original post. Closing the original post and opening a new post explicitly signals to the community the standards of interaction, and starting off fresh in a more positive way lets us move on and forgive, rather than having the initial post's tone and ensuing conversation always hanging over the discussion as it develops.

**Comment by choldgraf** [comment]
A quick clarification question - if there were a PR to the CoC, would that require quorum + 80% SC vote like in #66 ?

**Comment by choldgraf** [comment]
And just a note to what you said above - I totally agree with you about the importance of a "reset" rather than a "block" on the conversation.

That said, I'd like to avoid implying that the person *responding* to the CoC violation is also responsible for re-engaging conversation in a different thread. It's enough mental and emotional energy dealing with negativity on the internet (and I definitely don't have the energy for it) so I'd like to separate out the expectations for "putting a stop to CoC violations and preventing conversations spiraling downward" vs. "following up to improve the behavior in the future". Does that make sense?

**Comment by jasongrout** [comment]
> That said, I'd like to avoid implying that the person _responding_ to the CoC violation is also responsible for re-engaging conversation in a different thread.

Very good point. Yes, example language walking that line would be much appreciated!

**Comment by jasongrout** [comment]
> A quick clarification question - if there were a PR to the CoC, would that require quorum + 80% SC vote like in #66 ?

That's how I read the governance procedures in a strict sort of way.

Though since this is more of a helpful suggestion rather than a binding governance detail, I personally would have no objection to something like this being merged with less strict vote of approval.

**Comment by choldgraf** [comment]
Sounds good - I am happy to make a PR to propose some language for public forums etc, though I don't know that I have the energy to engage in a long debate process that needs to find 14 votes :-/

**Comment by jasongrout** [comment]
>  though I don't know that I have the energy to engage in a long debate process that needs to find 14 votes :-/

Again, since it is a suggestion rather than a binding procedure, I think you'll probably have an easier time than #66.

**Comment by mpacer** [comment]
I support this & am likely to approve it quickly. I don't think it is likely that you will get much resistance, just inaction. I would support a less strict approval requirement.

**Comment by choldgraf** [comment]
ok cool, I'll try and whip something up next week
